import React from "react";
import "./globals.css";

export const metadata = {
  title: "Robotic Insult Hurler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};